Growth dag improvement
Alodokter-Data/data-etl pull request #5
Opened 2021-04-06 02:40 UTC by khatyaputeri

Remove repetitive lines and using yaml file and loop

2021-04-06 02:56 UTC, diopratamadodoy approved these changes

2021-04-06 03:26 UTC, toileto requested changes

2021-04-06 03:26 UTC, toileto commented on dags/growth_big_dag_daily.py
> +for table in table:
Should be `tables` kan ya?

Is this tested @khatyaputeri?

2021-04-08 05:30 UTC, toileto approved these changes

2021-04-08 05:30 UTC, merged